"""add created_by and assigned_to to Task

Revision ID: 3287827219b2
Revises: 
Create Date: 2026-03-11 01:18:26.008313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3287827219b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to avoid batch and circular deps ###
    # add columns one at a time
    op.add_column('task', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('assigned_to', sa.Integer(), nullable=True))

    # create foreign keys on the table directly
    op.create_foreign_key(
        'fk_task_created_by_user', 'task', 'user', ['created_by'], ['id']
    )
    op.create_foreign_key(
        'fk_task_assigned_to_user', 'task', 'user', ['assigned_to'], ['id']
    )
    # ### end Alembic commands ###


def downgrade():
    # drop the foreign keys first
    op.drop_constraint('fk_task_assigned_to_user', 'task', type_='foreignkey')
    op.drop_constraint('fk_task_created_by_user', 'task', type_='foreignkey')

    # then remove the columns
    op.drop_column('task', 'assigned_to')
    op.drop_column('task', 'created_by')
    # ### end Alembic commands ###
