"""replace assigned_to with many-to-many TaskAssignee

Revision ID: 8204b7b92cd1
Revises: 3287827219b2
Create Date: 2026-03-11 02:01:29.235550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8204b7b92cd1'
down_revision = '3287827219b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_task_assigned_to_user', 'user', ['assigned_to'], ['id'])

    # ### end Alembic commands ###
