"""add profile_picture to Group model

Revision ID: b2691f401ff4
Revises: 2a4d7b32427f
Create Date: 2026-03-11 04:43:06.272486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2691f401ff4'
down_revision = '2a4d7b32427f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_poll')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key('fk_poll_created_by', 'user', ['created_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('created_by',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')

    op.create_table('_alembic_tmp_poll',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=300), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], name=op.f('fk_poll_created_by')),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
